# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='to_user',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=265),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
