# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_auto_20170410_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=265),
        ),
    ]
