# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0004_auto_20170410_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedin',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='LoggedIn',
        ),
    ]
